custom:
  authentication:
    jwt:
      accessToken: 3000000
      refreshToken: 6000000
    client:
      authorizedGrantTypes: refresh_token, client_credentials
      scope: openid, read, write

spring:
  datasource:
    url: jdbc:h2:mem:authorizedb
    driverClassName: org.h2.Driver
    username: admin
    password: admin
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

