INSERT INTO USER_CREDENTIALS(ID, USERNAME, PASSWORD) VALUES (901, 'pattawm8', '$2a$10$JhPhDCJHedrJXKbV.z6AcuGgRByHh3HJnH2vxCVBzuwEnUM4VBRFS');
INSERT INTO USER_CREDENTIALS(ID, USERNAME, PASSWORD)VALUES (902, 'nicola', '$2a$10$JhPhDCJHedrJXKbV.z6AcuGgRByHh3HJnH2vxCVBzuwEnUM4VBRFS');
INSERT INTO USER_CREDENTIALS(ID, USERNAME, PASSWORD) VALUES (903, 'john', '$2a$10$JhPhDCJHedrJXKbV.z6AcuGgRByHh3HJnH2vxCVBzuwEnUM4VBRFS');
INSERT INTO USER_CREDENTIALS(ID, USERNAME, PASSWORD) VALUES (904, 'stephen', '$2a$10$JhPhDCJHedrJXKbV.z6AcuGgRByHh3HJnH2vxCVBzuwEnUM4VBRFS');