version: '2'
services:
  elk:
    container_name: elk
    build: .
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411
